package src.main.java.com.gym17.gym17.model;
// Generated Sep 19, 2020, 1:05:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "heroku_4ee2ecbe460bfa4")
public class Contact implements java.io.Serializable {

	private int id;
	private String data;
	private String description;
	private int fkType;
	private int fkUser;

	public Contact() {
	}

	public Contact(int id, int fkType, int fkUser) {
		this.id = id;
		this.fkType = fkType;
		this.fkUser = fkUser;
	}

	public Contact(int id, String data, String description, int fkType, int fkUser) {
		this.id = id;
		this.data = data;
		this.description = description;
		this.fkType = fkType;
		this.fkUser = fkUser;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fk_type", nullable = false)
	public int getFkType() {
		return this.fkType;
	}

	public void setFkType(int fkType) {
		this.fkType = fkType;
	}

	@Column(name = "fk_user", nullable = false)
	public int getFkUser() {
		return this.fkUser;
	}

	public void setFkUser(int fkUser) {
		this.fkUser = fkUser;
	}

}
