package src.main.java.com.gym17.gym17.model;
// Generated Sep 28, 2020, 5:24:32 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", catalog = "heroku_4ee2ecbe460bfa4")
public class Discount implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Long value;
	private Set<ProductDiscount> productDiscounts = new HashSet<ProductDiscount>(0);

	public Discount() {
	}

	public Discount(String name, String description, Long value, Set<ProductDiscount> productDiscounts) {
		this.name = name;
		this.description = description;
		this.value = value;
		this.productDiscounts = productDiscounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "value", precision = 10, scale = 0)
	public Long getValue() {
		return this.value;
	}

	public void setValue(Long value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discount")
	public Set<ProductDiscount> getProductDiscounts() {
		return this.productDiscounts;
	}

	public void setProductDiscounts(Set<ProductDiscount> productDiscounts) {
		this.productDiscounts = productDiscounts;
	}

}
