package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupCustomer generated by hbm2java
 */
@Entity
@Table(name = "group_customer", catalog = "heroku_4ee2ecbe460bfa4")
public class GroupCustomer implements java.io.Serializable {

	private Integer id;
	private int fkCustomer;
	private int fkGroup;

	public GroupCustomer() {
	}

	public GroupCustomer(int fkCustomer, int fkGroup) {
		this.fkCustomer = fkCustomer;
		this.fkGroup = fkGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fk_customer", nullable = false)
	public int getFkCustomer() {
		return this.fkCustomer;
	}

	public void setFkCustomer(int fkCustomer) {
		this.fkCustomer = fkCustomer;
	}

	@Column(name = "fk_group", nullable = false)
	public int getFkGroup() {
		return this.fkGroup;
	}

	public void setFkGroup(int fkGroup) {
		this.fkGroup = fkGroup;
	}

}
