package src.main.java.com.gym17.gym17.model;
// Generated Apr 8, 2021, 1:55:16 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LuckyReward generated by hbm2java
 */
@Entity
@Table(name = "lucky_reward", catalog = "heroku_4ee2ecbe460bfa4")
public class LuckyReward implements java.io.Serializable {

	private Integer id;
	private RewardStatus rewardStatus;
	private UserCustomer userCustomer;
	private String name;
	private String description;
	private Date expirationDate;
	private String code;

	public LuckyReward() {
	}

	public LuckyReward(RewardStatus rewardStatus, UserCustomer userCustomer, String name, String description,
			Date expirationDate, String code) {
		this.rewardStatus = rewardStatus;
		this.userCustomer = userCustomer;
		this.name = name;
		this.description = description;
		this.expirationDate = expirationDate;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_reward_status")
	public RewardStatus getRewardStatus() {
		return this.rewardStatus;
	}

	public void setRewardStatus(RewardStatus rewardStatus) {
		this.rewardStatus = rewardStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_customer")
	public UserCustomer getUserCustomer() {
		return this.userCustomer;
	}

	public void setUserCustomer(UserCustomer userCustomer) {
		this.userCustomer = userCustomer;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
