package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MembershipFeeType generated by hbm2java
 */
@Entity
@Table(name = "membership_fee_type", catalog = "heroku_4ee2ecbe460bfa4")
public class MembershipFeeType implements java.io.Serializable {

	private Integer id;
	private long amount;
	private String description;
	private String name;
	private byte validityPeriod;

	public MembershipFeeType() {
	}

	public MembershipFeeType(long amount, String name, byte validityPeriod) {
		this.amount = amount;
		this.name = name;
		this.validityPeriod = validityPeriod;
	}

	public MembershipFeeType(long amount, String description, String name, byte validityPeriod) {
		this.amount = amount;
		this.description = description;
		this.name = name;
		this.validityPeriod = validityPeriod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "validity_period", nullable = false)
	public byte getValidityPeriod() {
		return this.validityPeriod;
	}

	public void setValidityPeriod(byte validityPeriod) {
		this.validityPeriod = validityPeriod;
	}

}
