package src.main.java.com.gym17.gym17.model;
// Generated Apr 8, 2021, 1:55:16 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PrivateCoachSchedule generated by hbm2java
 */
@Entity
@Table(name = "private_coach_schedule", catalog = "heroku_4ee2ecbe460bfa4")
public class PrivateCoachSchedule implements java.io.Serializable {

	private Integer id;
	private PrivateCoachStatus privateCoachStatus;
	@JsonIgnoreProperties(value = {"groupCustomers", "privateCoaches", "customerMembershipFees", "hibernateLazyInitializer"})
	private UserCustomer userCustomer;
	@JsonIgnoreProperties(value = {"groupWorkers", "privateCoaches", "userWorkerWorkerRightses", "hibernateLazyInitializer"})
	private UserWorker userWorker;
	private Weekdays weekdays;
	private String description;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date start;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date end;
	private Integer duration;
	 @JsonFormat(pattern="HH:mm:ss")
	private Date hour;

	public PrivateCoachSchedule() {
	}

	public PrivateCoachSchedule(PrivateCoachStatus privateCoachStatus, UserCustomer userCustomer, UserWorker userWorker,
			Weekdays weekdays, String description, Date start, Date end, Integer duration, Date hour) {
		this.privateCoachStatus = privateCoachStatus;
		this.userCustomer = userCustomer;
		this.userWorker = userWorker;
		this.weekdays = weekdays;
		this.description = description;
		this.start = start;
		this.end = end;
		this.duration = duration;
		this.hour = hour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_status")
	public PrivateCoachStatus getPrivateCoachStatus() {
		return this.privateCoachStatus;
	}

	public void setPrivateCoachStatus(PrivateCoachStatus privateCoachStatus) {
		this.privateCoachStatus = privateCoachStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_customer")
	public UserCustomer getUserCustomer() {
		return this.userCustomer;
	}

	public void setUserCustomer(UserCustomer userCustomer) {
		this.userCustomer = userCustomer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_worker")
	public UserWorker getUserWorker() {
		return this.userWorker;
	}

	public void setUserWorker(UserWorker userWorker) {
		this.userWorker = userWorker;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fk_weekday")
	public Weekdays getWeekdays() {
		return this.weekdays;
	}

	public void setWeekdays(Weekdays weekdays) {
		this.weekdays = weekdays;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", length = 19)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", length = 19)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hour", length = 8)
	public Date getHour() {
		return this.hour;
	}

	public void setHour(Date hour) {
		this.hour = hour;
	}

}
