package src.main.java.com.gym17.gym17.model;
// Generated Oct 5, 2020, 5:18:11 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * ProductDiscount generated by hbm2java
 */
@Entity
@Table(name = "product_discount", catalog = "heroku_4ee2ecbe460bfa4")
public class ProductDiscount implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Integer discountPercent;
	private String name;
	private String discountPrice;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date validFrom;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date validTo;
	private String discount;

	public ProductDiscount() {
	}

	public ProductDiscount(Product product, Integer discountPercent, String name, String discountPrice, Date validFrom,
			Date validTo, String discount) {
		this.product = product;
		this.discountPercent = discountPercent;
		this.name = name;
		this.discountPrice = discountPrice;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.discount = discount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_product")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "discount_percent")
	public Integer getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(Integer discountPercent) {
		this.discountPercent = discountPercent;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "discount_price", length = 250)
	public String getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(String discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 10)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", length = 10)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "discount", length = 250)
	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

}
