package src.main.java.com.gym17.gym17.model;
// Generated Sep 28, 2020, 5:24:32 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPdv generated by hbm2java
 */
@Entity
@Table(name = "product_pdv", catalog = "heroku_4ee2ecbe460bfa4")
public class ProductPdv implements java.io.Serializable {

	private Integer id;
	private Pdv pdv;
	private Product product;
	private String name;
	private String descriotion;
	private Date validFrom;
	private Date validTo;

	public ProductPdv() {
	}

	public ProductPdv(Pdv pdv, Product product, String name, String descriotion, Date validFrom, Date validTo) {
		this.pdv = pdv;
		this.product = product;
		this.name = name;
		this.descriotion = descriotion;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_pdv")
	public Pdv getPdv() {
		return this.pdv;
	}

	public void setPdv(Pdv pdv) {
		this.pdv = pdv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_product")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descriotion", length = 250)
	public String getDescriotion() {
		return this.descriotion;
	}

	public void setDescriotion(String descriotion) {
		this.descriotion = descriotion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 10)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", length = 10)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

}
