package src.main.java.com.gym17.gym17.model;
// Generated Sep 28, 2020, 5:24:32 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPrice generated by hbm2java
 */
@Entity
@Table(name = "product_price", catalog = "heroku_4ee2ecbe460bfa4")
public class ProductPrice implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String name;
	private String description;
	private Long value;
	private Date validFrom;

	public ProductPrice() {
	}

	public ProductPrice(Product product, String name, String description, Long value, Date validFrom) {
		this.product = product;
		this.name = name;
		this.description = description;
		this.value = value;
		this.validFrom = validFrom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_product")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "value", precision = 10, scale = 0)
	public Long getValue() {
		return this.value;
	}

	public void setValue(Long value) {
		this.value = value;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 10)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

}
