package src.main.java.com.gym17.gym17.model;
// Generated Sep 28, 2020, 5:24:32 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "heroku_4ee2ecbe460bfa4")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer fkType;
	private Long basePrice;
	private Integer productPdv;
	private Long priceWithPdv;
	private Set<ProductPdv> productPdvs = new HashSet<ProductPdv>(0);
	private Set<ProductDiscount> productDiscounts = new HashSet<ProductDiscount>(0);
	private Set<ProductPrice> productPrices = new HashSet<ProductPrice>(0);

	public Product() {
	}

	public Product(String name, String description, Integer fkType, Long basePrice, Integer productPdv,
			Long priceWithPdv, Set<ProductPdv> productPdvs, Set<ProductDiscount> productDiscounts,
			Set<ProductPrice> productPrices) {
		this.name = name;
		this.description = description;
		this.fkType = fkType;
		this.basePrice = basePrice;
		this.productPdv = productPdv;
		this.priceWithPdv = priceWithPdv;
		this.productPdvs = productPdvs;
		this.productDiscounts = productDiscounts;
		this.productPrices = productPrices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fk_type")
	public Integer getFkType() {
		return this.fkType;
	}

	public void setFkType(Integer fkType) {
		this.fkType = fkType;
	}

	@Column(name = "base_price", precision = 10, scale = 0)
	public Long getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(Long basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "product_pdv")
	public Integer getProductPdv() {
		return this.productPdv;
	}

	public void setProductPdv(Integer productPdv) {
		this.productPdv = productPdv;
	}

	@Column(name = "price_with_pdv", precision = 10, scale = 0)
	public Long getPriceWithPdv() {
		return this.priceWithPdv;
	}

	public void setPriceWithPdv(Long priceWithPdv) {
		this.priceWithPdv = priceWithPdv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductPdv> getProductPdvs() {
		return this.productPdvs;
	}

	public void setProductPdvs(Set<ProductPdv> productPdvs) {
		this.productPdvs = productPdvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductDiscount> getProductDiscounts() {
		return this.productDiscounts;
	}

	public void setProductDiscounts(Set<ProductDiscount> productDiscounts) {
		this.productDiscounts = productDiscounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductPrice> getProductPrices() {
		return this.productPrices;
	}

	public void setProductPrices(Set<ProductPrice> productPrices) {
		this.productPrices = productPrices;
	}

}
