package src.main.java.com.gym17.gym17.model;
// Generated Sep 28, 2020, 5:24:32 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * ProductDiscount generated by hbm2java
 */
@Entity
@Table(name = "product_discount", catalog = "heroku_4ee2ecbe460bfa4")
public class ProductDiscount implements java.io.Serializable {

	private Integer id;
	private Discount discount;
	private Product product;
	private String name;
	private String discount_1;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date validFrom;
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date validTo;

	public ProductDiscount() {
	}

	public ProductDiscount(Discount discount, Product product, String name, String discount_1, Date validFrom,
			Date validTo) {
		this.discount = discount;
		this.product = product;
		this.name = name;
		this.discount_1 = discount_1;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_discount")
	public Discount getDiscount() {
		return this.discount;
	}

	public void setDiscount(Discount discount) {
		this.discount = discount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_product")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "discount", length = 250)
	public String getDiscount_1() {
		return this.discount_1;
	}

	public void setDiscount_1(String discount_1) {
		this.discount_1 = discount_1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", length = 10)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", length = 10)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

}
