package src.main.java.com.gym17.gym17.model;
// Generated Apr 8, 2021, 1:55:16 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RewardStatus generated by hbm2java
 */
@Entity
@Table(name = "reward_status", catalog = "heroku_4ee2ecbe460bfa4")
public class RewardStatus implements java.io.Serializable {

	private Integer id;
	private String name;

	public RewardStatus() {
	}

	public RewardStatus(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
