package src.main.java.com.gym17.gym17.model;
// Generated Sep 30, 2020, 3:23:11 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "token", catalog = "heroku_4ee2ecbe460bfa4")
public class Token implements java.io.Serializable {

	private Integer id;
	private String licenceName;
	private String token;

	public Token() {
	}

	public Token(String licenceName, String token) {
		this.licenceName = licenceName;
		this.token = token;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "licenceName", length = 50)
	public String getLicenceName() {
		return this.licenceName;
	}

	public void setLicenceName(String licenceName) {
		this.licenceName = licenceName;
	}

	@Column(name = "token", length = 300)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
