package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserWorker generated by hbm2java
 */
@Entity
@Table(name = "user_worker", catalog = "heroku_4ee2ecbe460bfa4")
public class UserWorker implements java.io.Serializable {

	private int id;
	private WorkerType workerType;
	private String additionalData;
	private Set<PrivateCoach> privateCoaches = new HashSet<PrivateCoach>(0);

	public UserWorker() {
	}

	public UserWorker(int id) {
		this.id = id;
	}

	public UserWorker(int id, WorkerType workerType, String additionalData, Set<PrivateCoach> privateCoaches) {
		this.id = id;
		this.workerType = workerType;
		this.additionalData = additionalData;
		this.privateCoaches = privateCoaches;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_worker_type")
	public WorkerType getWorkerType() {
		return this.workerType;
	}

	public void setWorkerType(WorkerType workerType) {
		this.workerType = workerType;
	}

	@Column(name = "additional_data")
	public String getAdditionalData() {
		return this.additionalData;
	}

	public void setAdditionalData(String additionalData) {
		this.additionalData = additionalData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userWorker")
	public Set<PrivateCoach> getPrivateCoaches() {
		return this.privateCoaches;
	}

	public void setPrivateCoaches(Set<PrivateCoach> privateCoaches) {
		this.privateCoaches = privateCoaches;
	}

}
