package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserMembershipFee generated by hbm2java
 */
@Entity
@Table(name = "user_membership_fee", catalog = "heroku_4ee2ecbe460bfa4")
public class UserMembershipFee implements java.io.Serializable {

	private Integer id;
	private Date endDate;
	private int fkMembershipFee;
	private int fkUser;
	private Date startDate;

	public UserMembershipFee() {
	}

	public UserMembershipFee(Date endDate, int fkMembershipFee, int fkUser, Date startDate) {
		this.endDate = endDate;
		this.fkMembershipFee = fkMembershipFee;
		this.fkUser = fkUser;
		this.startDate = startDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "fk_membership_fee", nullable = false)
	public int getFkMembershipFee() {
		return this.fkMembershipFee;
	}

	public void setFkMembershipFee(int fkMembershipFee) {
		this.fkMembershipFee = fkMembershipFee;
	}

	@Column(name = "fk_user", nullable = false)
	public int getFkUser() {
		return this.fkUser;
	}

	public void setFkUser(int fkUser) {
		this.fkUser = fkUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}
