package src.main.java.com.gym17.gym17.model;
// Generated Sep 19, 2020, 1:05:34 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * UserCustomer generated by hbm2java
 */
@Entity
@Table(name = "user_customer", catalog = "heroku_4ee2ecbe460bfa4")
public class UserCustomer implements java.io.Serializable {

	private int id;
	@JsonIgnoreProperties(value = {"userCustomer", "activityLists", "userWorker", "hibernateLazyInitializer"})
	private User user;
	private String additionalData;
	@JsonIgnoreProperties("userCustomer")
	private Set<CustomerMembershipFee> customerMembershipFees = new HashSet<CustomerMembershipFee>(0);
	@JsonIgnoreProperties(value = {"userCustomer", "userWorker"})
	private Set<PrivateCoach> privateCoaches = new HashSet<PrivateCoach>(0);
	@JsonIgnoreProperties(value = {"groupCustomers", "groupWorkers", "userCustomer"})
	private Set<GroupCustomer> groupCustomers = new HashSet<GroupCustomer>(0);

	public UserCustomer() {
	}

	public UserCustomer(User user) {
		this.user = user;
	}

	public UserCustomer(User user, String additionalData, Set<CustomerMembershipFee> customerMembershipFees, Set<UserMembershipFee> userMembershipFees, Set<PrivateCoach> privateCoaches,
			Set<GroupCustomer> groupCustomers) {
		this.user = user;
		this.additionalData = additionalData;
		this.customerMembershipFees = customerMembershipFees;
		this.privateCoaches = privateCoaches;
		this.groupCustomers = groupCustomers;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "additional_data")
	public String getAdditionalData() {
		return this.additionalData;
	}

	public void setAdditionalData(String additionalData) {
		this.additionalData = additionalData;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCustomer", cascade = CascadeType.ALL)
	public Set<CustomerMembershipFee> getCustomerMembershipFees() {
		return this.customerMembershipFees;
	}

	public void setCustomerMembershipFees(Set<CustomerMembershipFee> customerMembershipFees) {
		this.customerMembershipFees = customerMembershipFees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCustomer", cascade = CascadeType.ALL)
	public Set<PrivateCoach> getPrivateCoaches() {
		return this.privateCoaches;
	}

	public void setPrivateCoaches(Set<PrivateCoach> privateCoaches) {
		this.privateCoaches = privateCoaches;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCustomer", cascade = CascadeType.ALL)
	public Set<GroupCustomer> getGroupCustomers() {
		return this.groupCustomers;
	}

	public void setGroupCustomers(Set<GroupCustomer> groupCustomers) {
		this.groupCustomers = groupCustomers;
	}

}
