package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserCustomer generated by hbm2java
 */
@Entity
@Table(name = "user_customer", catalog = "heroku_4ee2ecbe460bfa4")
public class UserCustomer implements java.io.Serializable {

	private int id;
	private String additionalData;
	private Set<PrivateCoach> privateCoaches = new HashSet<PrivateCoach>(0);

	public UserCustomer() {
	}

	public UserCustomer(int id) {
		this.id = id;
	}

	public UserCustomer(int id, String additionalData, Set<PrivateCoach> privateCoaches) {
		this.id = id;
		this.additionalData = additionalData;
		this.privateCoaches = privateCoaches;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "additional_data")
	public String getAdditionalData() {
		return this.additionalData;
	}

	public void setAdditionalData(String additionalData) {
		this.additionalData = additionalData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userCustomer")
	public Set<PrivateCoach> getPrivateCoaches() {
		return this.privateCoaches;
	}

	public void setPrivateCoaches(Set<PrivateCoach> privateCoaches) {
		this.privateCoaches = privateCoaches;
	}

}
