package src.main.java.com.gym17.gym17.model;
// Generated Sep 16, 2020, 7:54:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserWorkerWorkerRights generated by hbm2java
 */
@Entity
@Table(name = "user_worker_worker_rights", catalog = "heroku_4ee2ecbe460bfa4")
public class UserWorkerWorkerRights implements java.io.Serializable {

	private Integer id;
	private WorkerRights workerRights;
	private Boolean active;
	private Date created;
	private int fkWorker;

	public UserWorkerWorkerRights() {
	}

	public UserWorkerWorkerRights(WorkerRights workerRights, int fkWorker) {
		this.workerRights = workerRights;
		this.fkWorker = fkWorker;
	}

	public UserWorkerWorkerRights(WorkerRights workerRights, Boolean active, Date created, int fkWorker) {
		this.workerRights = workerRights;
		this.active = active;
		this.created = created;
		this.fkWorker = fkWorker;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_rights", nullable = false)
	public WorkerRights getWorkerRights() {
		return this.workerRights;
	}

	public void setWorkerRights(WorkerRights workerRights) {
		this.workerRights = workerRights;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "fk_worker", nullable = false)
	public int getFkWorker() {
		return this.fkWorker;
	}

	public void setFkWorker(int fkWorker) {
		this.fkWorker = fkWorker;
	}

}
