package src.main.java.com.gym17.gym17.model;
// Generated Sep 18, 2020, 8:04:59 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Weekdays generated by hbm2java
 */
@Entity
@Table(name = "weekdays", catalog = "heroku_4ee2ecbe460bfa4")
public class Weekdays implements java.io.Serializable {

	private Integer id;
	private String name;
	private String shortname;
	private Set<GroupWeekdays> groupWeekdayses = new HashSet<GroupWeekdays>(0);
	private Set<PrivateCoachWeekdays> privateCoachWeekdayses = new HashSet<PrivateCoachWeekdays>(0);

	public Weekdays() {
	}

	public Weekdays(String name, String shortname, Set<GroupWeekdays> groupWeekdayses,
			Set<PrivateCoachWeekdays> privateCoachWeekdayses) {
		this.name = name;
		this.shortname = shortname;
		this.groupWeekdayses = groupWeekdayses;
		this.privateCoachWeekdayses = privateCoachWeekdayses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "shortname", length = 5)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weekdays")
	public Set<GroupWeekdays> getGroupWeekdayses() {
		return this.groupWeekdayses;
	}

	public void setGroupWeekdayses(Set<GroupWeekdays> groupWeekdayses) {
		this.groupWeekdayses = groupWeekdayses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weekdays")
	public Set<PrivateCoachWeekdays> getPrivateCoachWeekdayses() {
		return this.privateCoachWeekdayses;
	}

	public void setPrivateCoachWeekdayses(Set<PrivateCoachWeekdays> privateCoachWeekdayses) {
		this.privateCoachWeekdayses = privateCoachWeekdayses;
	}

}
