package src.main.java.com.gym17.gym17.model;
// Generated Sep 19, 2020, 1:05:34 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WorkerRightsType generated by hbm2java
 */
@Entity
@Table(name = "worker_rights_type", catalog = "heroku_4ee2ecbe460bfa4")
public class WorkerRightsType implements java.io.Serializable {

	private Integer id;
	private String description;
	private String name;
	private Set<WorkerRights> workerRightses = new HashSet<WorkerRights>(0);

	public WorkerRightsType() {
	}

	public WorkerRightsType(String description, String name, Set<WorkerRights> workerRightses) {
		this.description = description;
		this.name = name;
		this.workerRightses = workerRightses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workerRightsType")
	public Set<WorkerRights> getWorkerRightses() {
		return this.workerRightses;
	}

	public void setWorkerRightses(Set<WorkerRights> workerRightses) {
		this.workerRightses = workerRightses;
	}

}
